### PR TITLE
Hidden outputFormat pref and support for bbl

### PR DESCRIPTION
**Pull request by KarlHegbloom**
- Adds hidden prefs under extensions.zotero.integration: hspace,
  maxmaxOffset, and outputFormat. Future plans include adding a
  prefs panel via a plugin to support the TeXmacs integration.
- Only outputFormat is ever used outside of checks for format 'bbl',
  which defaults to 'rtf' when the pref has not been set. Behavior for
  use with LibreOffice should be the same as before, except for:
- For any outputFormat, post-process citations and bibliographies to
  replace the abbreviation /X-X-X ?/g with "", so that setting an
  abbrev to "X-X-X" causes that thing and an optional trailing space
  to be removed completely. Setting an abbrev to the empty string is
  not possible since that's how the interface allows you to reset it
  to the default value.
- For the bbl outputFormat, replace spaces following periods within
  citations with hspace, so that TeXmacs will not put extra wide
  spaces after the periods in initials or abbreviations. It allows .!
  to be used to preserve the normal space there. This must be done at
  post-processing like this since the CSL processor does not know
  about ".} ", where a period is at the end of a TeX brace-enclosed
  format scoping group, with a space following it.
- Alternatively, if that proves to interfere with use of the 'bbl
  outputFormat for use with regular TeX or LaTeX, the similar munging
  can instead be performed by the TeXmacs side of the integration. Of
  course for TeX or LaTeX, defining the hspace macro is simple.

### CODE REVIEW

**Comment by fbennett** [comment]
Sorry for the delay in getting to this, Karl. I'll go though it this weekend.

**Comment by KarlHegbloom** [comment]
Thanks.  No hurry. Please try the TeXmacs integration.  I know you'll like
it,  since you are the author of LexiTeX.

**Comment by fbennett** [comment]
That was a _long_ time ago! But I'll try to check it out!

**Comment by KarlHegbloom** [comment]
Do you like this better?

I'm thinking of monkey-patching, so I can do potentially disruptive work on extending the customization ability for the bibliography, to add support for select, exclude, and quash.

**Comment by fbennett** [comment]
Is this still live? (Sorry for the long delay---I've just finished a massive round of work on cites in our current round of Masters theses, and I'm trying to tidy up before plunging into Zotero 5.0 migration work.)

I have a question on one item:

> For any outputFormat, post-process citations and bibliographies to
> replace the abbreviation /X-X-X ?/g with "", so that setting an
> abbrev to "X-X-X" causes that thing and an optional trailing space
> to be removed completely. Setting an abbrev to the empty string is
> not possible since that's how the interface allows you to reset it
> to the default value.

Is this with the Abbreviation Filter plugin? If so, AF has a (hackish) suppression mechanism already. For the abbreviated variable, it would be:

```
!here>>>
```

**Comment by KarlHegbloom** [comment]
I have changed to using a monkey-patch,  based initially on your
propachi-upper... See: https://github.com/KarlHegbloom/propachi-texmacs and
https://github.com/KarlHegbloom/citeproc-js on branch
KarlHegbloom-propachi-texmacs where I'm developing the bbl outputFormat.

See: https://github.com/KarlHegbloom/zotero-texmacs-integration for how I'm
using these. The README.md links to sample documents, a video screencast,
and there's a PDF of its' documentation in the doc directory.

I've moved the X-X-X thing out to the scheme code in
zotero-texmacs-integration. I did find the !here>>> hack finally. Take a
look at what I've done to get categorized table of authorities while also
hiding things like "Supreme Court". To make supreme court sort ahead of
appellate court, I can prepend a two digit number and #@, and those figure
into sorting but get stripped before rendering,  by scheme code in
zotero.scm inside TeXmacs. When it finds a string repeated twice and
followed by X-X-X, it strips it out, so that the item can sort where it
belongs,  yet the string used for sorting can be not rendered: 00#@Sup.
Ct.Sup. Ct.X-X-X

I can also make "dummy" entries with the title set like
000000000@#\ztbibSubHeading{!Subheading
Title goes Here} and use the editBibliography integration interface to add
them,  and it strips out the extra stuff,  and renders a subheading in the
bibliography.

Let's leave this as a monkey-patch until I am sure that the bbl
outputFormat is stable enough,  and perhaps also either tested with LaTeX
or renamed to indicate that it's special to the TeXmacs integration.  I
have a guile scheme script that is the start of a drop in replacement for
bibtex, but it uses BBT, and he's changed the interface,  so I need to
update it before it will run again. It could make a thebibliography from an
aux file,  but did not handle in text citations that did not appear as
numbers or authorDate. It could be extended to support BibLaTeX. With the
abstraction macros I've moved to for TeXmacs, I think they can be defined
in LaTeX to expand into regular bibtex ones,  or whatever.

**Comment by fbennett** [comment]
Karl,

Changes went into the Abbreviation Filter with v5.0.36m14 a few days ago, along with a change to the CSL-M schema (adding a `country` variable that carries a country code snipped off the front of `jurisdiction`). I'm not sure whether this will impact your work in TexMacs.

After a stream of promises and false starts, Juris-M 5.0 is now stable, and I'm finally getting stuck into clearing backlog items. I'll look at this PR in the next few days and ping back if I have any questions.

**Comment by fbennett** [comment]
Ha. First question already. Would your integration plugin still be a viable drop-in substitute for the LibreOffice plugin from Zotero main?

**Comment by fbennett** [comment]
@KarlHegbloom This has been languishing. Is monkey-patching working well for you? From a maintenance perspective, I'm a little nervous about the impact on code inherited from Zotero.

**Pull request closed without merging**
