### PR TITLE
Make panes resizable in classic integration dialog

### PR DESCRIPTION
**Pull request by KarlHegbloom**
In the editBibliographyDialog and the classic addCitationDialog, the
collection and selected items panes were too small and it did not allow
them to be resized. This commit fixes it.

### CODE REVIEW

**Comment by KarlHegbloom** [comment]
The panes are resizeable, and I can drag the columns around to arrange them the way I like, but the zotero-persist thing is not functioning the way I expect. The item is written to prefs.js, but when the dialog is called for again, it has the default arrangement again. What's wrong?

**Comment by fbennett** [comment]
Karl: Thanks for this! It persists for me here, under Linux with LibreOffice. After stopping the word processor and Firefox and restarting both, I get the custom configuration. What is your platform?

**Comment by fbennett** [comment]
In testing, I built a pre-pull-request version, and it also persisted and allowed rearrangement of columns - so on Linux, at least, this seems to work out of the box. What platform are you testing on?

**Comment by KarlHegbloom** [comment]
Ubuntu 16.04, kept current. I'll try again next time I sit down with it.
I'm out running errands today.

**Comment by fbennett** [comment]
Thanks! Sorry for the long delay in adopting this -- I've cherry-picked the change into the jurism-5.0 tree, with a note.

**Pull request closed without merging**
